### ISSUE TITLE
How to get the 'test_lag.csv' ?

### ISSUE THREAD

**Issue by lllchi** [anhquan0412/Predict_Future_Sales#1]

**Comment by anhquan0412** [comment]
Unfortunately I don't have that piece of code to generate test_lag.csv with me right now and I didn't include it purposely because this Kaggle competition is a final project of an online course on Coursera and they don't encourage sharing all details. However you can still generate test_lag.csv with the same code in generate_lag_feature notebook by concatenating test.csv to the end of all_data + perform the month_shift loop + get the test portion back from all_data

Here's a quick pseucode code:
```
all_data = pd.read_csv(data_path+'new_sales.csv')
test = pd.read_csv('test.csv')


#Pseudocode for preprocess_test function:
#Performing merge to get item_name and item_category_id on test set
#Set all 'target', 'shop_block_target_sum', 'shop_block_target_mean', 'item_block_target_sum', 'item_block_target_mean', 'item_cat_block_target_sum', 'item_cat_block_target_mean' to 0 (placeholder)
#Set date_block_num to 34 (as we predict Nov 2015)
test = preprocess_test(test)

all_data = pd.concatenate(all_data,test)

#perform month_shift loop on test set, as described in generate_lag_features to get [1,2,3,5,12] lag features
#generate holiday features as well
all_data = get_lag_and_holiday(all_data)
#get the test set back. This should be equivalent to test_lag.csv
test_lag = all_data[all_data.date_block_num==34].copy()
```
These are just pseudocode, not actual code., but it will help you get that test_lag.csv

**Comment by yiluzhuimeng** [comment]
Set all 'target', 'shop_block_target_sum', 'shop_block_target_mean', 'item_block_target_sum', 'item_block_target_mean', 'item_cat_block_target_sum', 'item_cat_block_target_mean' to 0 (placeholder)？why set 0?  it is not the real,  Does it harm to the result?

**Comment by Lg955** [comment]
@lllchi So do you know how to generate the test_lag.csv? I meet the same problem.
